# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clls.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clls.proto',
  package='',
  serialized_pb='\n\nclls.proto\"\xc9\x02\n\x10WiFiAccessoPunto\x12\r\n\x05\x62ssid\x18\x01 \x02(\t\x12,\n\x08location\x18\x02 \x01(\x0b\x32\x1a.WiFiAccessoPunto.Location\x12\x0f\n\x07\x63hannel\x18\x15 \x01(\x05\x1a\xe6\x01\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x03\x12\x11\n\tlongitude\x18\x02 \x01(\x03\x12\x10\n\x08unknown3\x18\x03 \x01(\x03\x12\x10\n\x08unknown4\x18\x04 \x01(\x03\x12\x10\n\x08unknown5\x18\x05 \x01(\x03\x12\x10\n\x08unknown6\x18\x06 \x01(\x03\x12\x10\n\x08unknown7\x18\x07 \x01(\x03\x12\x10\n\x08unknown8\x18\x08 \x01(\x03\x12\x10\n\x08unknown9\x18\t \x01(\x03\x12\x11\n\tunknown10\x18\n \x01(\x03\x12\x11\n\tunknown11\x18\x0b \x01(\x03\x12\x11\n\tunknown12\x18\x0c \x01(\x03\"d\n\x08\x63llswloc\x12\x10\n\x08unknown1\x18\x01 \x01(\x03\x12\x1d\n\x02\x61p\x18\x02 \x03(\x0b\x32\x11.WiFiAccessoPunto\x12\x10\n\x08unknown3\x18\x03 \x01(\x05\x12\x15\n\rget_neighbour\x18\x04 \x01(\x05')




_WIFIACCESSOPUNTO_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='WiFiAccessoPunto.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='WiFiAccessoPunto.Location.latitude', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='WiFiAccessoPunto.Location.longitude', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown3', full_name='WiFiAccessoPunto.Location.unknown3', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown4', full_name='WiFiAccessoPunto.Location.unknown4', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown5', full_name='WiFiAccessoPunto.Location.unknown5', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown6', full_name='WiFiAccessoPunto.Location.unknown6', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown7', full_name='WiFiAccessoPunto.Location.unknown7', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown8', full_name='WiFiAccessoPunto.Location.unknown8', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown9', full_name='WiFiAccessoPunto.Location.unknown9', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown10', full_name='WiFiAccessoPunto.Location.unknown10', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown11', full_name='WiFiAccessoPunto.Location.unknown11', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown12', full_name='WiFiAccessoPunto.Location.unknown12', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=114,
  serialized_end=344,
)

_WIFIACCESSOPUNTO = _descriptor.Descriptor(
  name='WiFiAccessoPunto',
  full_name='WiFiAccessoPunto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bssid', full_name='WiFiAccessoPunto.bssid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='WiFiAccessoPunto.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='WiFiAccessoPunto.channel', index=2,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_WIFIACCESSOPUNTO_LOCATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=344,
)


_CLLSWLOC = _descriptor.Descriptor(
  name='cllswloc',
  full_name='cllswloc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='cllswloc.unknown1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ap', full_name='cllswloc.ap', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown3', full_name='cllswloc.unknown3', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_neighbour', full_name='cllswloc.get_neighbour', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=346,
  serialized_end=446,
)

_WIFIACCESSOPUNTO_LOCATION.containing_type = _WIFIACCESSOPUNTO;
_WIFIACCESSOPUNTO.fields_by_name['location'].message_type = _WIFIACCESSOPUNTO_LOCATION
_CLLSWLOC.fields_by_name['ap'].message_type = _WIFIACCESSOPUNTO
DESCRIPTOR.message_types_by_name['WiFiAccessoPunto'] = _WIFIACCESSOPUNTO
DESCRIPTOR.message_types_by_name['cllswloc'] = _CLLSWLOC

class WiFiAccessoPunto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Location(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _WIFIACCESSOPUNTO_LOCATION

    # @@protoc_insertion_point(class_scope:WiFiAccessoPunto.Location)
  DESCRIPTOR = _WIFIACCESSOPUNTO

  # @@protoc_insertion_point(class_scope:WiFiAccessoPunto)

class cllswloc(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLLSWLOC

  # @@protoc_insertion_point(class_scope:cllswloc)


# @@protoc_insertion_point(module_scope)
